name: Update Impressions

on:
  schedule:
#    - cron: '0 0 * * *'  # 毎日0時0分に実行
  workflow_dispatch:  # 手動で実行するオプションを追加

jobs:
  update_impressions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # 必要なPythonのバージョンを指定

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # requirements.txtから依存関係をインストール

    - name: Run script to update impressions
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}  # GitHub Secretsから取得
        GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}  # GitHub Secretsから取得
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}  # GitHub Secretsから取得
      run: |
        python update_impressions.py  # Pythonスクリプトを実行
